version: "2.4"
services:
  home_assistant:
    container_name: "home-assistant"
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /docker/volumes/home-assistant/config:/config
    network_mode: host
    restart: always
    environment:
      - TZ=Europe/Athens
  zigbee2mqtt:
    container_name: "zigbee2mqtt"
    image: koenkk/zigbee2mqtt
    volumes:
      - /run/udev:/run/udev:ro
      - /docker/volumes/zigbee2mqtt/data:/app/data
    devices:
      - /dev/ttyACM0
    network_mode: host
    restart: always
    privileged: true
    environment:
      - TZ=Europe/Athens
  mosquitto:
    container_name: "mosquitto"
    image: eclipse-mosquitto
    volumes:
      - /docker/volumes/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /docker/volumes/mosquitto/data:/mosquitto/data
      - /docker/volumes/mosquitto/log:/mosquitto/log
    network_mode: host
    restart: always
    environment:
      - TZ=Europe/Athens
  postgres:
    container_name: "postgres"
    image: postgres:13.2-alpine
    volumes:
      - /docker/volumes/postgres:/var/lib/postgresql/data
    network_mode: host
    restart: always
    environment:
      POSTGRES_PASSWORD: "MyHash"
